import 'dart:io';
import 'package:flutter/services.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'health_archive/health_archive_service.dart';
import 'health_archive/models.dart';
import 'health_archive/health_context_builder.dart';

class CaregiverExportService {
  static final CaregiverExportService _instance = CaregiverExportService._internal();
  factory CaregiverExportService() => _instance;
  CaregiverExportService._internal();

  Future<void> exportHealthProfileToPdf() async {
    final pdf = pw.Document();
    final profile = await HealthArchiveService().getFullProfile();
    final contextBuilder = HealthContextBuilder(HealthArchiveService());
    await contextBuilder.initialize();
    final symptoms = await contextBuilder.getActiveSymptoms();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Text('Health Profile Export (Caregiver Copy)',
                  style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
            ),
            pw.SizedBox(height: 10),
            pw.Text('Generated by Med Assist App', style: pw.TextStyle(color: PdfColors.grey)),
            pw.SizedBox(height: 20),

            _buildSection(
              title: 'Chronic Conditions',
              content: profile.conditions.map((c) => '- ${c.name} (Onset: ${c.onsetYear ?? "Unknown"})').toList(),
            ),

            pw.SizedBox(height: 15),

            _buildSection(
              title: 'Current Medications',
              content: profile.medications.map((m) => '- ${m.name} ${m.dosage} (${m.frequency})').toList(),
            ),

            pw.SizedBox(height: 15),

            _buildSection(
              title: 'Allergies',
              content: profile.allergies.map((a) => '- ${a.allergen} (${a.severity?.name ?? "Unknown"})').toList(),
            ),
            
            pw.SizedBox(height: 15),

            _buildSection(
              title: 'Recent Active Symptoms',
              content: symptoms.map((s) => '- ${s.name} (${s.severity.name}, since ${s.onsetDate.toString().split(' ')[0]})').toList(),
            ),
          ];
        },
      ),
    );

    // Prompt user to share/save the PDF
    await Printing.sharePdf(
      bytes: await pdf.save(),
      filename: 'health_profile_${DateTime.now().millisecondsSinceEpoch}.pdf',
    );
  }

  pw.Widget _buildSection({required String title, required List<String> content}) {
    if (content.isEmpty) {
      return pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
          pw.SizedBox(height: 5),
          pw.Text('None recorded.', style: pw.TextStyle(fontStyle: pw.FontStyle.italic, color: PdfColors.grey600)),
        ],
      );
    }
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(title, style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold, color: PdfColors.blueGrey800)),
        pw.SizedBox(height: 5),
        ...content.map((text) => pw.Text(text, style: const pw.TextStyle(fontSize: 14))),
      ],
    );
  }
}
